---
- name: Install required site packages
  ansible.builtin.package:
    name: "{{ packages_site }}"
    state: present
  become: true
  become_user: root
  when: packages_site | default([]) | length > 0

- name: Install required group packages
  ansible.builtin.package:
    name: "{{ packages_group }}"
    state: present
  become: true
  become_user: root
  when:
    - packages_group | default([]) | length > 0

- name: Install required host packages
  ansible.builtin.package:
    name: "{{ packages_host }}"
    state: present
  become: true
  become_user: root
  when:
    - packages_host | default([]) | length > 0
    - "'client' in group_names"

- name: Set default editor
  community.general.alternatives:
    name: editor
    path: "{{ packages_editor }}"
    priority: 100
  become: true
  become_user: root
  when: packages_editor | length > 0
  ignore_errors: "{{ ansible_check_mode }}"
