---
- name: Install required site packages
  ansible.builtin.package:
    name: "{{ packages.site }}"
    state: present
  when: packages.site | default([]) | length > 0

- name: Install required server packages
  ansible.builtin.package:
    name: "{{ packages.server }}"
    state: present
  when:
    - packages.server | default([]) | length > 0
    - "'client' not in group_names"

- name: Install required client packages
  ansible.builtin.package:
    name: "{{ packages.client }}"
    state: present
  when:
    - packages.client | default([]) | length > 0
    - "'client' in group_names"

- name: Install required client python packages
  ansible.builtin.pip:
    name: "{{ packages.client_pip }}"
    state: present
  when:
    - packages.client_pip | default([]) | length > 0
    - "'client' in group_names"

- name: Set default editor
  community.general.alternatives:
    name: editor
    path: "{{ packages.editor }}"
    priority: 100
  when: packages.editor | length > 0
  ignore_errors: "{{ ansible_check_mode }}"
