---
- name: Install required site packages
  ansible.builtin.package:
    name: "{{ packages_site }}"
    state: present
  become: true
  become_user: root
  when: packages_site | default([]) | length > 0

- name: Install required server packages
  ansible.builtin.package:
    name: "{{ packages.server }}"
    state: present
  become: true
  become_user: root
  when:
    - packages.server | default([]) | length > 0
    - "'client' not in group_names"

- name: Install required client packages
  ansible.builtin.package:
    name: "{{ packages_client }}"
    state: present
  become: true
  become_user: root
  when:
    - packages_client | default([]) | length > 0
    - "'client' in group_names"

- name: Set default editor
  community.general.alternatives:
    name: editor
    path: "{{ packages_editor }}"
    priority: 100
  become: true
  become_user: root
  when: packages_editor | length > 0
  ignore_errors: "{{ ansible_check_mode }}"
